# Cloud Build configuration

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud logging write-log --log-name=cloud_build_log --severity=INFO --message="Build completed"']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_ACCOUNT: '' # Removed service_account requirement
