apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eclaims

resources:
  - ../../base

# Image tag substitution — CI/CD injects actual tag
images:
  - name: REGISTRY/eclaims/claims-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/claims-service
    newTag: latest
  - name: REGISTRY/eclaims/notification-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/notification-service
    newTag: latest
  - name: REGISTRY/eclaims/document-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/document-service
    newTag: latest
  - name: REGISTRY/eclaims/partner-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/partner-service
    newTag: latest
  - name: REGISTRY/eclaims/workflow-service
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/workflow-service
    newTag: latest
  - name: REGISTRY/eclaims/api-gateway
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/api-gateway
    newTag: latest
  - name: REGISTRY/eclaims/frontend
    newName: us-central1-docker.pkg.dev/PROJECT_ID/eclaims/frontend
    newTag: latest

patches:
  # Scale claims-service to 3 replicas in prod
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: claims-service

  # Scale partner-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: partner-service
