apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eclaims-dev

resources:
  - ../../base

nameSuffix: "-dev"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

images:
  - name: REGISTRY/eclaims/claims-service
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/claims-service
    newTag: latest
  - name: REGISTRY/eclaims/notification-service
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/notification-service
    newTag: latest
  - name: REGISTRY/eclaims/document-service
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/document-service
    newTag: latest
  - name: REGISTRY/eclaims/partner-service
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/partner-service
    newTag: latest
  - name: REGISTRY/eclaims/workflow-service
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/workflow-service
    newTag: latest
  - name: REGISTRY/eclaims/api-gateway
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/api-gateway
    newTag: latest
  - name: REGISTRY/eclaims/frontend
    newName: us-central1-docker.pkg.dev/eclaims-promotioncasestudy/eclaims/frontend
    newTag: latest
